package com.spendwise

class Constants {

    companion object {
        private var countryCurrencyMap = mapOf<String, String>(
            "Afghanistan" to "؋",
            "Albania" to "L",
            "Algeria" to "د.ج",
            "Andorra" to "€",
            "Angola" to "Kz",
            "Antigua and Barbuda" to "$",
            "Argentina" to "$",
            "Armenia" to "֏",
            "Australia" to "$",
            "Austria" to "€",
            "Azerbaijan" to "₼",
            "Bahamas" to "$",
            "Bahrain" to ".د.ب",
            "Bangladesh" to "৳",
            "Barbados" to "$",
            "Belarus" to "Br",
            "Belgium" to "€",
            "Belize" to "$",
            "Benin" to "CFA",
            "Bhutan" to "Nu.",
            "Bolivia" to "Bs.",
            "Bosnia and Herzegovina" to "KM",
            "Botswana" to "P",
            "Brazil" to "R$",
            "Brunei" to "$",
            "Bulgaria" to "лв",
            "Burkina Faso" to "CFA",
            "Burundi" to "Fr",
            "Cambodia" to "៛",
            "Cameroon" to "CFA",
            "Canada" to "$",
            "Cape Verde" to "CVE",
            "Central African Republic" to "CFA",
            "Chad" to "CFA",
            "Chile" to "$",
            "China" to "¥",
            "Colombia" to "$",
            "Comoros" to "Fr",
            "Congo, Democratic Republic of the" to "CDF",
            "Congo, Republic of the" to "CFA",
            "Costa Rica" to "₡",
            "Croatia" to "kn",
            "Cuba" to "$",
            "Cyprus" to "€",
            "Czech Republic" to "Kč",
            "Denmark" to "kr",
            "Djibouti" to "Fr",
            "Dominica" to "$",
            "Dominican Republic" to "RD$",
            "East Timor" to "USD",
            "Ecuador" to "USD",
            "Egypt" to "ج.م",
            "El Salvador" to "$",
            "Equa torial Guinea" to "CFA",
            "Eritrea" to "Nfk",
            "Es tonia" to "€",
            "Eswatini" to "SZL",
            "Ethiopia" to "ETB",
            "Fiji" to "$",
            "Finland" to "€",
            "France" to "€",
            "Gabon" to "CFA",
            "Gambia" to "GMD",
            "Georgia" to "₾",
            "Germany" to "€",
            "Ghana" to "₵",
            "Greece" to "€",
            "Grenada" to "$",
            "Guatemala" to "Q",
            "Guinea" to "GNF",
            "Guinea-Bissau" to "CFA",
            "Guyana" to "$",
            "Haiti" to "G",
            "Honduras" to "L",
            "Hungary" to "Ft",
            "Iceland" to "kr",
            "India" to "₹",
            "Indonesia" to "Rp",
            "Iran" to "﷼",
            "Iraq" to "ع.د",
            "Ireland" to "€",
            "Israel" to "₪",
            "Italy" to "€",
            "Jamaica" to "J$",
            "Japan" to "¥",
            "Jordan" to "د.ا",
            "Kazakhstan" to "₸",
            "Kenya" to "KSh",
            "Kiribati" to "$",
            "Korea, North" to "₩",
            "Korea, South" to "₩",
            "Kosovo" to "€",
            "Kuwait" to "د.ك",
            "Kyrgyzstan" to "лв",
            "Laos" to "₭",
            "Latvia" to "€",
            "Lebanon" to "ل.ل",
            "Lesotho" to "L",
            "Liberia" to "L$",
            "Libya" to "ل.د",
            "Liechtenstein" to "CHF",
            "Lithuania" to "€",
            "Luxembourg" to "€",
            "Madagascar" to "Ar",
            "Malawi" to "MK",
            "Malaysia" to "RM",
            "Maldives" to "ރ.",
            "Mali" to "CFA",
            "Malta" to "€",
            "Marshall Islands" to "$",
            "Mauritania" to "MRU",
            "Mauritius" to "₨",
            "Mexico" to "$",
            "Micronesia" to "$",
            "Moldova" to "MDL",
            "Monaco" to "€",
            "Mongolia" to "₮",
            "Montenegro" to "€",
            "Morocco" to "د.م.",
            "Mozambique" to "MT",
            "Myanmar" to "Ks",
            "Namibia" to "$",
            "Nauru" to "$",
            "Nepal" to "₨",
            "Netherlands" to "€",
            "New Zealand" to "$",
            "Nicaragua" to "C$",
            "Niger" to "CFA",
            "Nigeria" to "₦",
            "North Macedonia" to "ден",
            "Norway" to "kr",
            "Oman" to "ر.ع.",
            "Pakistan" to "₨",
            "Palau" to "$",
            "Panama" to "B/.",
            "Papua New Guinea" to "K",
            "Paraguay" to "₲",
            "Peru" to "S/.",
            "Philippines" to "₱",
            "Poland" to "zł",
            "Portugal" to "€",
            "Qatar" to "ر.ق",
            "Romania" to "lei",
            "Russia" to "₽",
            "Rwanda" to "Fr",
            "Saint Kitts and Nevis" to "$",
            "Saint Lucia" to "$",
            "Saint Vincent and the Grenadines" to "$",
            "Samoa" to "T",
            "San Marino" to "€",
            "Sao  tome and Principe" to "Db",
            "Saudi Arabia" to "﷼",
            "Senegal" to "CFA",
            "Serbia" to "дин.",
            "Seychelles" to "₨",
            "Sierra Leone" to "Le",
            "Singapore" to "$",
            "Slovakia" to "€",
            "Slovenia" to "€",
            "Solomon Islands" to "$",
            "Somalia" to "S",
            "South Africa" to "R",
            "South Sudan" to "£",
            "Spain" to "€",
            "Sri Lanka" to "Rs",
            "Sudan" to "SDG",
            "Suriname" to "$",
            "Sweden" to "kr",
            "Switzerland" to "Fr",
            "Syria" to "£",
            "Taiwan" to "NT$",
            "Tajikistan" to "ЅМ",
            "Tanzania" to "Sh",
            "Thailand" to "฿",
            " togo" to "CFA",
            " tonga" to "T$",
            "Trinidad and  tobago" to "TT$",
            "Tunisia" to "د.ت",
            "Turkey" to "₺",
            "Turkmenistan" to "T",
            "Tuvalu" to "$",
            "Uganda" to "Sh",
            "Ukraine" to "₴",
            "United Arab Emirates" to "AED",
            "United Kingdom" to "£",
            "United States" to "$",
            "Uruguay" to "$",
            "Uzbekistan" to "so'm",
            "Vanuatu" to "Vt",
            "Vatican City" to "€",
            "Venezuela" to "Bs.",
            "Vietnam" to "₫",
            "Yemen" to "﷼",
            "Zambia" to "ZK",
            "Zimbabwe" to "Z$"
        )
        private var countryCurrencyMapShortForms = mapOf<String, String>(
            "Afghanistan" to "AFN",
            "Albania" to "ALL",
            "Algeria" to "DZD",
            "Andorra" to "EUR",
            "Angola" to "AOA",
            "Antigua and Barbuda" to "XCD",
            "Argentina" to "ARS",
            "Armenia" to "AMD",
            "Australia" to "AUD",
            "Austria" to "EUR",
            "Azerbaijan" to "AZN",
            "Bahamas" to "BSD",
            "Bahrain" to "BHD",
            "Bangladesh" to "BDT",
            "Barbados" to "BBD",
            "Belarus" to "BYN",
            "Belgium" to "EUR",
            "Belize" to "BZD",
            "Benin" to "XOF",
            "Bhutan" to "BTN",
            "Bolivia" to "BOB",
            "Bosnia and Herzegovina" to "BAM",
            "Botswana" to "BWP",
            "Brazil" to "BRL",
            "Brunei" to "BND",
            "Bulgaria" to "BGN",
            "Burkina Faso" to "XOF",
            "Burundi" to "BIF",
            "Cambodia" to "KHR",
            "Cameroon" to "XAF",
            "Canada" to "CAD",
            "Cape Verde" to "CVE",
            "Central African Republic" to "XAF",
            "Chad" to "XAF",
            "Chile" to "CLP",
            "China" to "CNY",
            "Colombia" to "COP",
            "Comoros" to "KMF",
            "Congo, Democratic Republic of the" to "CDF",
            "Congo, Republic of the" to "XAF",
            "Costa Rica" to "CRC",
            "Croatia" to "HRK",
            "Cuba" to "CUP",
            "Cyprus" to "EUR",
            "Czech Republic" to "CZK",
            "Denmark" to "DKK",
            "Djibouti" to "DJF",
            "Dominica" to "XCD",
            "Dominican Republic" to "DOP",
            "East Timor" to "USD",
            "Ecuador" to "USD",
            "Egypt" to "EGP",
            "El Salvador" to "USD",
            "Equatorial Guinea" to "XAF",
            "Eritrea" to "ERN",
            "Estonia" to "EUR",
            "Eswatini" to "SZL",
            "Ethiopia" to "ETB",
            "Fiji" to "FJD",
            "Finland" to "EUR",
            "France" to "EUR",
            "Gabon" to "XAF",
            "Gambia" to "GMD",
            "Georgia" to "GEL",
            "Germany" to "EUR",
            "Ghana" to "GHS",
            "Greece" to "EUR",
            "Grenada" to "XCD",
            "Guatemala" to "GTQ",
            "Guinea" to "GNF",
            "Guinea-Bissau" to "XOF",
            "Guyana" to "GYD",
            "Haiti" to "HTG",
            "Honduras" to "HNL",
            "Hungary" to "HUF",
            "Iceland" to "ISK",
            "India" to "INR",
            "Indonesia" to "IDR",
            "Iran" to "IRR",
            "Iraq" to "IQD",
            "Ireland" to "EUR",
            "Israel" to "ILS",
            "Italy" to "EUR",
            "Jamaica" to "JMD",
            "Japan" to "JPY",
            "Jordan" to "JOD",
            "Kazakhstan" to "KZT",
            "Kenya" to "KES",
            "Kiribati" to "AUD",
            "Korea, North" to "KPW",
            "Korea, South" to "KRW",
            "Kosovo" to "EUR",
            "Kuwait" to "KWD",
            "Kyrgyzstan" to "KGS",
            "Laos" to "LAK",
            "Latvia" to "EUR",
            "Lebanon" to "LBP",
            "Lesotho" to "LSL",
            "Liberia" to "LRD",
            "Libya" to "LYD",
            "Liechtenstein" to "CHF",
            "Lithuania" to "EUR",
            "Luxembourg" to "EUR",
            "Madagascar" to "MGA",
            "Malawi" to "MWK",
            "Malaysia" to "MYR",
            "Maldives" to "MVR",
            "Mali" to "XOF",
            "Malta" to "EUR",
            "Marshall Islands" to "USD",
            "Mauritania" to "MRU",
            "Mauritius" to "MUR",
            "Mexico" to "MXN",
            "Micronesia" to "USD",
            "Moldova" to "MDL",
            "Monaco" to "EUR",
            "Mongolia" to "MNT",
            "Montenegro" to "EUR",
            "Morocco" to "MAD",
            "Mozambique" to "MZN",
            "Myanmar" to "MMK",
            "Namibia" to "NAD",
            "Nauru" to "AUD",
            "Nepal" to "NPR",
            "Netherlands" to "EUR",
            "New Zealand" to "NZD",
            "Nicaragua" to "NIO",
            "Niger" to "XOF",
            "Nigeria" to "NGN",
            "North Macedonia" to "MKD",
            "Norway" to "NOK",
            "Oman" to "OMR",
            "Pakistan" to "PKR",
            "Palau" to "USD",
            "Panama" to "PAB",
            "Papua New Guinea" to "PGK",
            "Paraguay" to "PYG",
            "Peru" to "PEN",
            "Philippines" to "PHP",
            "Poland" to "PLN",
            "Portugal" to "EUR",
            "Qatar" to "QAR",
            "Romania" to "RON",
            "Russia" to "RUB",
            "Rwanda" to "RWF",
            "Saint Kitts and Nevis" to "XCD",
            "Saint Lucia" to "XCD",
            "Saint Vincent and the Grenadines" to "XCD",
            "Samoa" to "WST",
            "San Marino" to "EUR",
            "Sao Tome and Principe" to "STN",
            "Saudi Arabia" to "SAR",
            "Senegal" to "XOF",
            "Serbia" to "RSD",
            "Seychelles" to "SCR",
            "Sierra Leone" to "SLL",
            "Singapore" to "SGD",
            "Slovakia" to "EUR",
            "Slovenia" to "EUR",
            "Solomon Islands" to "SBD",
            "Somalia" to "SOS",
            "South Africa" to "ZAR",
            "South Sudan" to "SSP",
            "Spain" to "EUR",
            "Sri Lanka" to "LKR",
            "Sudan" to "SDG",
            "Suriname" to "SRD",
            "Sweden" to "SEK",
            "Switzerland" to "CHF",
            "Syria" to "SYP",
            "Taiwan" to "TWD",
            "Tajikistan" to "TJS",
            "Tanzania" to "TZS",
            "Thailand" to "THB",
            "Togo" to "XOF",
            "Tonga" to "TOP",
            "Trinidad and Tobago" to "TTD",
            "Tunisia" to "TND",
            "Turkey" to "TRY",
            "Turkmenistan" to "TMT",
            "Tuvalu" to "AUD",
            "Uganda" to "UGX",
            "Ukraine" to "UAH",
            "United Arab Emirates" to "AED",
            "United Kingdom" to "GBP",
            "United States" to "USD",
            "Uruguay" to "UYU",
            "Uzbekistan" to "UZS",
            "Vanuatu" to "VUV",
            "Vatican City" to "EUR",
            "Venezuela" to "VES",
            "Vietnam" to "VND",
            "Yemen" to "YER",
            "Zambia" to "ZMW",
            "Zimbabwe" to "ZWL"
        )


        const val TABLE_CREDIT = "table_credit"
        const val TABLE_EXPENSE = "table_expense"
        const val BACKUP_FOLDER_NAME = "SpendWise_BACKUP"
        const val BACKUP_FILE_NAME = "SpendWise_backup.db"
        const val DATABASE_NAME = "ExpenseDetails.db"
        const val flight_data_access_token = "e763dfbfb40cd8a2dcca4e0b91261004"


        fun getMap(): Map<String, String> = countryCurrencyMap
        fun getMapShort(): Map<String, String> = countryCurrencyMapShortForms

    }


}