package com.spendwise

class Constants {

    companion object {
        private var countryCurrencyMap = mapOf<String, String>(
            "Afghanistan" to "؋",
            "Albania" to "L",
            "Algeria" to "د.ج",
            "Andorra" to "€",
            "Angola" to "Kz",
            "Antigua and Barbuda" to "$",
            "Argentina" to "$",
            "Armenia" to "֏",
            "Australia" to "$",
            "Austria" to "€",
            "Azerbaijan" to "₼",
            "Bahamas" to "$",
            "Bahrain" to ".د.ب",
            "Bangladesh" to "৳",
            "Barbados" to "$",
            "Belarus" to "Br",
            "Belgium" to "€",
            "Belize" to "$",
            "Benin" to "CFA",
            "Bhutan" to "Nu.",
            "Bolivia" to "Bs.",
            "Bosnia and Herzegovina" to "KM",
            "Botswana" to "P",
            "Brazil" to "R$",
            "Brunei" to "$",
            "Bulgaria" to "лв",
            "Burkina Faso" to "CFA",
            "Burundi" to "Fr",
            "Cambodia" to "៛",
            "Cameroon" to "CFA",
            "Canada" to "$",
            "Cape Verde" to "CVE",
            "Central African Republic" to "CFA",
            "Chad" to "CFA",
            "Chile" to "$",
            "China" to "¥",
            "Colombia" to "$",
            "Comoros" to "Fr",
            "Congo, Democratic Republic of the" to "CDF",
            "Congo, Republic of the" to "CFA",
            "Costa Rica" to "₡",
            "Croatia" to "kn",
            "Cuba" to "$",
            "Cyprus" to "€",
            "Czech Republic" to "Kč",
            "Denmark" to "kr",
            "Djibouti" to "Fr",
            "Dominica" to "$",
            "Dominican Republic" to "RD$",
            "East Timor" to "USD",
            "Ecuador" to "USD",
            "Egypt" to "ج.م",
            "El Salvador" to "$",
            "Equa torial Guinea" to "CFA",
            "Eritrea" to "Nfk",
            "Es tonia" to "€",
            "Eswatini" to "SZL",
            "Ethiopia" to "ETB",
            "Fiji" to "$",
            "Finland" to "€",
            "France" to "€",
            "Gabon" to "CFA",
            "Gambia" to "GMD",
            "Georgia" to "₾",
            "Germany" to "€",
            "Ghana" to "₵",
            "Greece" to "€",
            "Grenada" to "$",
            "Guatemala" to "Q",
            "Guinea" to "GNF",
            "Guinea-Bissau" to "CFA",
            "Guyana" to "$",
            "Haiti" to "G",
            "Honduras" to "L",
            "Hungary" to "Ft",
            "Iceland" to "kr",
            "India" to "₹",
            "Indonesia" to "Rp",
            "Iran" to "﷼",
            "Iraq" to "ع.د",
            "Ireland" to "€",
            "Israel" to "₪",
            "Italy" to "€",
            "Jamaica" to "J$",
            "Japan" to "¥",
            "Jordan" to "د.ا",
            "Kazakhstan" to "₸",
            "Kenya" to "KSh",
            "Kiribati" to "$",
            "Korea, North" to "₩",
            "Korea, South" to "₩",
            "Kosovo" to "€",
            "Kuwait" to "د.ك",
            "Kyrgyzstan" to "лв",
            "Laos" to "₭",
            "Latvia" to "€",
            "Lebanon" to "ل.ل",
            "Lesotho" to "L",
            "Liberia" to "L$",
            "Libya" to "ل.د",
            "Liechtenstein" to "CHF",
            "Lithuania" to "€",
            "Luxembourg" to "€",
            "Madagascar" to "Ar",
            "Malawi" to "MK",
            "Malaysia" to "RM",
            "Maldives" to "ރ.",
            "Mali" to "CFA",
            "Malta" to "€",
            "Marshall Islands" to "$",
            "Mauritania" to "MRU",
            "Mauritius" to "₨",
            "Mexico" to "$",
            "Micronesia" to "$",
            "Moldova" to "MDL",
            "Monaco" to "€",
            "Mongolia" to "₮",
            "Montenegro" to "€",
            "Morocco" to "د.م.",
            "Mozambique" to "MT",
            "Myanmar" to "Ks",
            "Namibia" to "$",
            "Nauru" to "$",
            "Nepal" to "₨",
            "Netherlands" to "€",
            "New Zealand" to "$",
            "Nicaragua" to "C$",
            "Niger" to "CFA",
            "Nigeria" to "₦",
            "North Macedonia" to "ден",
            "Norway" to "kr",
            "Oman" to "ر.ع.",
            "Pakistan" to "₨",
            "Palau" to "$",
            "Panama" to "B/.",
            "Papua New Guinea" to "K",
            "Paraguay" to "₲",
            "Peru" to "S/.",
            "Philippines" to "₱",
            "Poland" to "zł",
            "Portugal" to "€",
            "Qatar" to "ر.ق",
            "Romania" to "lei",
            "Russia" to "₽",
            "Rwanda" to "Fr",
            "Saint Kitts and Nevis" to "$",
            "Saint Lucia" to "$",
            "Saint Vincent and the Grenadines" to "$",
            "Samoa" to "T",
            "San Marino" to "€",
            "Sao  tome and Principe" to "Db",
            "Saudi Arabia" to "﷼",
            "Senegal" to "CFA",
            "Serbia" to "дин.",
            "Seychelles" to "₨",
            "Sierra Leone" to "Le",
            "Singapore" to "$",
            "Slovakia" to "€",
            "Slovenia" to "€",
            "Solomon Islands" to "$",
            "Somalia" to "S",
            "South Africa" to "R",
            "South Sudan" to "£",
            "Spain" to "€",
            "Sri Lanka" to "Rs",
            "Sudan" to "SDG",
            "Suriname" to "$",
            "Sweden" to "kr",
            "Switzerland" to "Fr",
            "Syria" to "£",
            "Taiwan" to "NT$",
            "Tajikistan" to "ЅМ",
            "Tanzania" to "Sh",
            "Thailand" to "฿",
            " togo" to "CFA",
            " tonga" to "T$",
            "Trinidad and  tobago" to "TT$",
            "Tunisia" to "د.ت",
            "Turkey" to "₺",
            "Turkmenistan" to "T",
            "Tuvalu" to "$",
            "Uganda" to "Sh",
            "Ukraine" to "₴",
            "United Arab Emirates" to "AED",
            "United Kingdom" to "£",
            "United States" to "$",
            "Uruguay" to "$",
            "Uzbekistan" to "so'm",
            "Vanuatu" to "Vt",
            "Vatican City" to "€",
            "Venezuela" to "Bs.",
            "Vietnam" to "₫",
            "Yemen" to "﷼",
            "Zambia" to "ZK",
            "Zimbabwe" to "Z$"
        )


        val TABLE_CREDIT = "table_credit"
        val TABLE_EXPENSE = "table_expense"

        fun getMap(): Map<String, String> = countryCurrencyMap

    }


}